# Generated by Django 3.1.1 on 2020-09-20 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200920_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_list',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movie.movielist'),
        ),
    ]
