# Generated by Django 3.1.1 on 2020-09-20 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200920_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movielist'),
        ),
    ]
