# Generated by Django 3.1.1 on 2020-09-20 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0004_auto_20200920_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='movie_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
