# Generated by Django 3.1.1 on 2020-09-20 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0005_movielist_movie_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielist',
            name='movie_list',
        ),
        migrations.AddField(
            model_name='movielist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
