# Generated by Django 3.1.1 on 2020-09-20 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200920_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielist',
            old_name='user',
            new_name='user_list',
        ),
    ]
