# Generated by Django 3.1.1 on 2020-09-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20200920_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='movie_name',
        ),
        migrations.RenameField(
            model_name='movielist',
            old_name='name',
            new_name='list_name',
        ),
        migrations.RenameField(
            model_name='movielist',
            old_name='user_list',
            new_name='user_name',
        ),
    ]
