# Generated by Django 3.1.1 on 2020-09-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20200920_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_name',
            new_name='name',
        ),
    ]
